name: test        # name: ワークフローの名前
on: push          # on: いつこのワークフローを走らせるか（例：push時）
jobs:             # jobs: 実行したい処理（ジョブ）のリスト
  test:           # testという名前のジョブを定義
    runs-on: ubuntu-latest   # 実行環境（GitHubが用意するUbuntu仮想マシン）
    steps:                   # ジョブの中で行う手続き
      - uses: actions/checkout@v3  # ソースコードを取得する（必須）
      - name: All test             # このステップの名前
        run: bash -xv ./test.bash  # 実際にテストスクリプトを実行

